DROP TABLE IF EXISTS Band CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS BandGenre CASCADE;
DROP TABLE IF EXISTS Concert CASCADE;
DROP TABLE IF EXISTS BandLink CASCADE;
DROP TABLE IF EXISTS Member CASCADE;
DROP TABLE IF EXISTS BandFavourite CASCADE;